/* eslint-disable */
/**
 * Generated by scripts/codegen.ts. Do not edit; run `pnpm run codegen`.
 */

import type * as agentStore from "../agentStore.js";
import type * as approvals from "../approvals.js";
import type * as assistant from "../assistant.js";
import type * as brain from "../brain.js";
import type * as codex from "../codex.js";
import type * as composio from "../composio.js";
import type * as connectorAccounts from "../connectorAccounts.js";
import type * as conversations from "../conversations.js";
import type * as crons from "../crons.js";
import type * as dashboard from "../dashboard.js";
import type * as history from "../history.js";
import type * as http from "../http.js";
import type * as ingest from "../ingest.js";
import type * as installation from "../installation.js";
import type * as jobs from "../jobs.js";
import type * as lib_agent from "../lib/agent.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_commands from "../lib/commands.js";
import type * as lib_errors from "../lib/errors.js";
import type * as lib_telegram from "../lib/telegram.js";
import type * as lib_telegramFormat from "../lib/telegramFormat.js";
import type * as lib_truncate from "../lib/truncate.js";
import type * as mcp from "../mcp.js";
import type * as media from "../media.js";
import type * as memories from "../memories.js";
import type * as models from "../models.js";
import type * as notify from "../notify.js";
import type * as persona from "../persona.js";
import type * as recovery from "../recovery.js";
import type * as runner from "../runner.js";
import type * as runs from "../runs.js";
import type * as secrets from "../secrets.js";
import type * as tools from "../tools.js";
import type * as web from "../web.js";
import type * as work from "../work.js";

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";

declare const fullApi: ApiFromModules<{
  agentStore: typeof agentStore;
  approvals: typeof approvals;
  assistant: typeof assistant;
  brain: typeof brain;
  codex: typeof codex;
  composio: typeof composio;
  connectorAccounts: typeof connectorAccounts;
  conversations: typeof conversations;
  crons: typeof crons;
  dashboard: typeof dashboard;
  history: typeof history;
  http: typeof http;
  ingest: typeof ingest;
  installation: typeof installation;
  jobs: typeof jobs;
  "lib/agent": typeof lib_agent;
  "lib/auth": typeof lib_auth;
  "lib/commands": typeof lib_commands;
  "lib/errors": typeof lib_errors;
  "lib/telegram": typeof lib_telegram;
  "lib/telegramFormat": typeof lib_telegramFormat;
  "lib/truncate": typeof lib_truncate;
  mcp: typeof mcp;
  media: typeof media;
  memories: typeof memories;
  models: typeof models;
  notify: typeof notify;
  persona: typeof persona;
  recovery: typeof recovery;
  runner: typeof runner;
  runs: typeof runs;
  secrets: typeof secrets;
  tools: typeof tools;
  web: typeof web;
  work: typeof work;
}>;

/** Functions the dashboard, the runner and scripts can call, e.g. `api.dashboard.getChat`. */
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;

/** Functions only the backend itself calls, e.g. `internal.brain.handleTurn`. */
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
