/* eslint-disable */
// Generated by scripts/codegen.ts. Do not edit; run `pnpm run codegen`.
// Every module in convex/, by the name its functions are called by.

import * as agentStore from "../convex/agentStore";
import * as approvals from "../convex/approvals";
import * as assistant from "../convex/assistant";
import * as brain from "../convex/brain";
import * as codex from "../convex/codex";
import * as composio from "../convex/composio";
import * as connectorAccounts from "../convex/connectorAccounts";
import * as conversations from "../convex/conversations";
import * as crons from "../convex/crons";
import * as dashboard from "../convex/dashboard";
import * as history from "../convex/history";
import * as http from "../convex/http";
import * as ingest from "../convex/ingest";
import * as installation from "../convex/installation";
import * as jobs from "../convex/jobs";
import * as lib_agent from "../convex/lib/agent";
import * as lib_auth from "../convex/lib/auth";
import * as lib_commands from "../convex/lib/commands";
import * as lib_errors from "../convex/lib/errors";
import * as lib_telegram from "../convex/lib/telegram";
import * as lib_telegramFormat from "../convex/lib/telegramFormat";
import * as lib_truncate from "../convex/lib/truncate";
import * as mcp from "../convex/mcp";
import * as media from "../convex/media";
import * as memories from "../convex/memories";
import * as models from "../convex/models";
import * as notify from "../convex/notify";
import * as persona from "../convex/persona";
import * as recovery from "../convex/recovery";
import * as runner from "../convex/runner";
import * as runs from "../convex/runs";
import * as secrets from "../convex/secrets";
import * as tools from "../convex/tools";
import * as web from "../convex/web";
import * as work from "../convex/work";

export const modules: Record<string, Record<string, unknown>> = {
  "agentStore": agentStore,
  "approvals": approvals,
  "assistant": assistant,
  "brain": brain,
  "codex": codex,
  "composio": composio,
  "connectorAccounts": connectorAccounts,
  "conversations": conversations,
  "crons": crons,
  "dashboard": dashboard,
  "history": history,
  "http": http,
  "ingest": ingest,
  "installation": installation,
  "jobs": jobs,
  "lib/agent": lib_agent,
  "lib/auth": lib_auth,
  "lib/commands": lib_commands,
  "lib/errors": lib_errors,
  "lib/telegram": lib_telegram,
  "lib/telegramFormat": lib_telegramFormat,
  "lib/truncate": lib_truncate,
  "mcp": mcp,
  "media": media,
  "memories": memories,
  "models": models,
  "notify": notify,
  "persona": persona,
  "recovery": recovery,
  "runner": runner,
  "runs": runs,
  "secrets": secrets,
  "tools": tools,
  "web": web,
  "work": work,
};
