#!/usr/bin/env bun
/**
 * `pnpm run codegen`: what Convex's CLI used to generate, now that Perry runs
 * its backend itself.
 *
 *   convex/_generated/api.d.ts   the types of `api` and `internal`: every module
 *                                in convex/, so `api.dashboard.getChat` is typed
 *   server/modules.ts            the same modules, imported, for the server to
 *                                find each function by its name
 *
 * Run after adding or removing a file in convex/. The build runs it too.
 */

import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const convexDir = join(root, "convex");
const SKIP = new Set(["schema.ts", "convex.config.ts"]);

function modules(dir: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith("_") || entry.name.startsWith(".")) continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...modules(path));
    else if (entry.name.endsWith(".ts") && !entry.name.endsWith(".d.ts") && !SKIP.has(entry.name)) {
      found.push(relative(convexDir, path).replace(/\\/g, "/").replace(/\.ts$/, ""));
    }
  }
  return found.sort();
}

const names = modules(convexDir);
const ident = (name: string) => name.replace(/[^A-Za-z0-9]/g, "_");
const key = (name: string) => /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);

const api = `/* eslint-disable */
/**
 * Generated by scripts/codegen.ts. Do not edit; run \`pnpm run codegen\`.
 */

${names.map((name) => `import type * as ${ident(name)} from "../${name}.js";`).join("\n")}

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";

declare const fullApi: ApiFromModules<{
${names.map((name) => `  ${key(name)}: typeof ${ident(name)};`).join("\n")}
}>;

/** Functions the dashboard, the runner and scripts can call, e.g. \`api.dashboard.getChat\`. */
export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;

/** Functions only the backend itself calls, e.g. \`internal.brain.handleTurn\`. */
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
`;

const server = `/* eslint-disable */
// Generated by scripts/codegen.ts. Do not edit; run \`pnpm run codegen\`.
// Every module in convex/, by the name its functions are called by.

${names.map((name) => `import * as ${ident(name)} from "../convex/${name}";`).join("\n")}

export const modules: Record<string, Record<string, unknown>> = {
${names.map((name) => `  ${JSON.stringify(name)}: ${ident(name)},`).join("\n")}
};
`;

writeFileSync(join(convexDir, "_generated", "api.d.ts"), api);
writeFileSync(join(root, "server", "modules.ts"), server);
console.log(`codegen: ${names.length} modules`);
